name: Cypress Tests

on:
  push:
    branches: [ main, dev, master, develop ]
  pull_request:
    branches: [ main, dev, master, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CI: 'true'

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4   # ✅ Correct version
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
